name: État des comptes
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  etat-des-comptes:
    runs-on: ubuntu-latest
    steps:
      - name: Clone data repository
        run: |
          git clone --depth 1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} .
      - name: Installer et lancer l'état des comptes ⚙️
        run: |
          npm ci
          npm run etat-des-comptes
      - name: Rajouter les fichiers 
        run: |
          git add etat-des-comptes.yml
          git commit -a -m "Rajout de l'état des comptes"
      - name: Pousser le résultat dans une branche 'résultat'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'résultat'
      
